spring:
  data:
    cassandra:
      keyspace-name: test
      username: NUhLATNGBOjvjkUPNNqHrvUj
      password: 6378wbFznhn7ru5ZKxIhJTchiMv0hEgmbRZkYejmAXzUZh.R,6ErJjPGuynMTYs8PLDfqKW.00LZfP5H_uQ7mQxDHCsjdpU94r1YA+_Pck1Cvb,32+6MOruC-SKcqdFZ
      schema-action: create-if-not-exists
      #ssl: false
      request:
        timeout: 60s
      connection:
        connect-timeout: 60s
        init-query-timeout: 60s
datastax.astra:
  secure-connect-bundle: secure-connect-workshops.zip

astra.db:
  id: f3b39a93-7359-48cb-b250-52e2a2bb6d54-1
  region: asia-south1
  keyspace: test
  application.token: AstraCS:NUhLATNGBOjvjkUPNNqHrvUj:26e16eba1a17100d4a0c782127bafcd5f3bcc86ce271979c1b1b7a1a32d70ca5

server:
  port: 8089

